import './globals.scss'
import type { Metadata } from 'next'
import { Params } from 'next/dist/shared/lib/router/utils/route-matcher'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: Params
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          className={`w-screen min-h-screen flex flex-col items-center justify-center bg-bg_primary relative ${
            params?.locale === 'ar' || params?.locale === 'fa' ? 'rtl' : ''
          }`}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
